### ISSUE TITLE
Add support for Microsoft Teams

### ISSUE THREAD

**Issue by floyare** [Lumm1t/anti-testportal#11]
This script is not working in Microsoft Teams or I'm doing something wrong but If i'll paste this code into console in MS Teams it's not working.

**Comment by darvd29** [comment]
Yes, you are doing something wrong. This script is for testportal.net, not for MS Teams.

**Comment by Lumm1t** [comment]
It's working in Microsoft Teams, don't paste code into console, just follow tutorial.

- Go to the Releases page (then download newest version (.zip)) - https://github.com/Lumm1t/anti-testportal/releases/tag/v3.0.0.
- Unpack ZIP file.
- Go to the extensions page (chrome://extensions or Chrome menu -> More tools -> Extensions).
- Enable Developer mode (upper right corner).
- Click Load unpacked (or drag the folder anywhere on the page).
- Indicate the folder you unpacked.

**Comment by gbaranski** [comment]
What do you mean with Microsoft Teams? Tests on it are safe and you can leave page whenever you want.

**Comment by floyare** [comment]
I mean, It's not working in application.

**Comment by Lumm1t** [comment]
Of course this is not working in ms teams app, it's browser extension, it's working only in web (http://teams.microsoft.com)
