### ISSUE TITLE
"hOnEsT ReSpOnDeNt tEcHnOlOgY" seems to detect tab movement (kinda)

### ISSUE THREAD

**Issue by Ruseriousss** [Lumm1t/anti-testportal#15]
Hi, Lumm1t, excellent work on the Extension so far, also thanks a ton on the regular improvements to the extension. 

However, I recently noticed a weird thing while using the extension in Testportal. 

**Suppose I write a test with 20 questions. 
I finish all the 20 questions and go back to the some other previous question for rechecking or something. 
The hOnEsT ReSpOnDeNt tEcHnOlOgY thing comes up and it says that your tab movement has been detected and you will be blocked from giving this test.** 

1) This thing comes up only when going hopping from question to some other random question. 

(For example - from question 18 to question 3)

2) I noticed this pattern only when moving from a question to another question in the descending order.

(For example - from question 10 to question 8)

3) I haven't been consistently able to replicate this, but I will surely send a pic of it as soon as I am able to.

_I can assure you no tabs except the testportal tab were open, neither was I changing the tabs nor were any background programs open or running._

**Comment by gbaranski** [comment]
@Ruseriousss if that happens only when moving to next question, that might be because extension hasn't fully loaded, but testportal "hOnEsT ReSpOnDeNt tEcHnOlOgY" is loaded. Especially because they are using SSR and classic redirects.

**Comment by Ruseriousss** [comment]
Hi, Lumm1t.
I haven't been able to replicate this issue since the past few days. I am unsure whether this was occurring due to something on my end or something else. Regardless, thanks to your Coding Wizardry :) this stuff doesn't occur anymore so I will close this issue.

**Once Again, Thanks a ton.**
