### ISSUE TITLE
Can't install extension

### ISSUE THREAD

**Issue by SmoGroove** [Lumm1t/anti-testportal#19]
![image](https://user-images.githubusercontent.com/75605318/101320926-d2d52080-3864-11eb-8ea1-ed33215c82ca.png)

**Comment by gbaranski** [comment]
@SmoGroove Can you follow the instructions? Download the extension from releases or from chrome web store.

**Comment by SmoGroove** [comment]
yeah i followed all instructions. I downloaded it form releases. It's unavailable on chrome web store

**Comment by SmoGroove** [comment]
Solved, Zip file was broken
