### ISSUE TITLE
"hOnEsT rEsPoNdEnT tEcHnOlOgy" skip no longer works.

### ISSUE THREAD

**Issue by Ruseriousss** [Lumm1t/anti-testportal#4]
Hi, Lumm1t. It's been really great using this extension. It has worked well for me over the past three months or so. Anyways, I requested you to fix the issue which I asked you to fix last week. Once again, I want to thank you for that. So here's the issue:

Earlier, I would be able to switch tabs  with no problem with the extension enabled but, now it no longer works. Below are the pictures: 

https://user-images.githubusercontent.com/66557345/93012469-67531e00-f5a9-11ea-8a00-6bc2c9081f97.png

https://user-images.githubusercontent.com/66557345/93012471-69b57800-f5a9-11ea-8b98-40051ae263cf.png

Anyways thanks a ton for the assistance.

**Comment by Lumm1t** [comment]
I'll fix it today.

**Comment by Ruseriousss** [comment]
I truly respect your dedication to help me. Thank you very much.

**Comment by Lumm1t** [comment]
v2.6 is working for me, can you give me your test link?

**Comment by Lumm1t** [comment]
`If time has elapsed, don't do anything. onCountdownFinished = () => {};`
It doesn't work, will fix it soon.

**Comment by Ruseriousss** [comment]
Yeah, sure I just made the test for lols to test the honest thingy. Here ya
go:

https://www.testportal.net/test.html?t=TcP4Km2eBbh8

**Comment by Ruseriousss** [comment]
Hi, Lumm1t. I don't really know if this information helps or not. But, I noticed that when I set value of Blocking the Test when switching tabs to greater than 1. The Honest Respondent thing doesn't block me. Also, the thing in which you could enter the question even when time elapsed also doesn't work.

https://user-images.githubusercontent.com/66557345/93172512-ad3bed80-f733-11ea-8c13-0ccff3f732a5.JPG


Anyways, thanks a ton.

**Comment by Lumm1t** [comment]
`$(window).blur(() => eraseCookie('blurs'));`
Cookie 'blurs' is almost always set to 1, that's why you get kicked from test, when switching tabs is set to 1.

**Comment by Lumm1t** [comment]
Maybe i'll fix it.

**Comment by Ruseriousss** [comment]
Thanks a lot.

>

**Comment by Ruseriousss** [comment]
Hi, Lumm1t, I just realized what I wrote earlier was wrong in which I told you I had set the value to 1 and it wouldn't work. A bit of digging later, I found that the testportal honest thing does detect your browser tab changes but won't show the warning. However, it will block you if you exceed the given value. Also, in the previous comment I had stated that the 'do nothing after time elapses thing doesn't work' I checked it once more and its the same. (I wrote this statement once more so that you could differentiate that my statement of value 1 thing is false/incorrect and time elapse thing is true)

I am really sorry if my behavior annoys/bugs you. I sincerely apologize.

**Comment by Lumm1t** [comment]
Fixed in newest update.
