### ISSUE TITLE
Już nie działa

### ISSUE THREAD

**Issue by MrCyjaneK** [Lumm1t/anti-testportal#5]
![image](https://user-images.githubusercontent.com/20381330/96369474-743fd000-115a-11eb-8014-7b0c87faf42d.png)

Problem występuje gdy w konsoli wpisze się `document.hasFocus = (() => {return true})`

**Comment by Lumm1t** [comment]
Dlaczego próbujesz to robić? Testportal wykrywa nadpisanie document.hasFocus i blokuje dostęp do testu.
Pobierz najnowszą wersję (https://github.com/Lumm1t/anti-testportal/releases/tag/v3.0.0) i ją wgraj zgodnie z poradnikiem.

**Comment by MrCyjaneK** [comment]
:+1:
